name: Run Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Clear npm cache
      run: npm cache clean --force

    - name: Delete package-lock.json
      run: rm package-lock.json

    - name: Install Dependencies
      run: npm install

    - name: Run Tests
      run: npm run test:coverage
